// src/packages/angular/src/Avatar.component.ts
import { ChangeDetectionStrategy, Component, Input, OnChanges, SimpleChanges } from "@angular/core";
import { createAvatar, type AvatarOptions, type Style } from "@avatar-generator/core";

/**
 * Angular component for rendering avatars
 *
 * @example
 * ```html
 * <avatar-generator
 *   [style]="initialsStyle"
 *   [options]="{ seed: 'Hugo GB', size: 64 }"
 *   alt="User avatar"
 * />
 * ```
 */
@Component({
    selector: "avatar-generator",
    template: `<img [src]="dataUri" [alt]="alt" [width]="size" [height]="size" />`,
    changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AvatarComponent<T extends AvatarOptions> implements OnChanges {
    /** The style to use for generating the avatar */
    @Input() style!: Style<T>;

    /** Options for the avatar (varies by style) */
    @Input() options!: T;

    /** Alt text for accessibility */
    @Input() alt = "Avatar";

    /** Generated data URI for the SVG */
    dataUri = "";

    /** Size for the image element */
    size = 64;

    ngOnChanges(_changes: SimpleChanges): void {
        if (this.style && this.options) {
            this.renderAvatar();
        }
    }

    private renderAvatar(): void {
        const avatar = createAvatar(this.style, this.options);
        this.dataUri = avatar.toDataUri();
        this.size = this.options.size ?? 64;
    }
}

// src/packages/react/src/Avatar.tsx
import {
  createAvatar,
  type AvatarOptions,
  type AvatarResult,
  type Style,
} from "@avatar-generator/core";
import * as React from "react";

/**
 * Props for the Avatar component
 */
interface AvatarProps<T extends AvatarOptions> {
  /** The style to use for generating the avatar */
  style: Style<T>;
  /** Options for the avatar (varies by style) */
  options: T;
  /** Additional CSS class names */
  className?: string;
  /** Alt text for accessibility */
  alt?: string;
}

/**
 * React component for rendering avatars
 *
 * @example
 * ```tsx
 * import { Avatar } from '@avatar-generator/react';
 * import { initials } from '@avatar-generator/style-initials';
 *
 * function UserAvatar({ name }: { name: string }) {
 *   return (
 *     <Avatar
 *       style={initials}
 *       options={{ seed: name, size: 48 }}
 *       alt={name}
 *     />
 *   );
 * }
 * ```
 */
function Avatar<T extends AvatarOptions>({
  style,
  options,
  className,
  alt,
}: AvatarProps<T>): React.ReactElement {
  const avatar: AvatarResult = React.useMemo(
    () => createAvatar(style, options),
    [style, options],
  );

  return (
    <img
      src={avatar.toDataUri()}
      alt={alt ?? "Avatar"}
      className={className}
      width={options.size ?? 64}
      height={options.size ?? 64}
    />
  );
}

export default Avatar;
export { Avatar };
export type { AvatarProps };
